// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZhWIsp4giRk3RtNklClNuQHyh-4stEU',
    appId: '1:489954207593:web:fcaf821841c9be17963ff8',
    messagingSenderId: '489954207593',
    projectId: 'resell-itv2',
    authDomain: 'resell-itv2.firebaseapp.com',
    storageBucket: 'resell-itv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJa8YcpRuLNJY_6YRMoQOYOxMwvM6d-I',
    appId: '1:489954207593:android:9005abc070c30264963ff8',
    messagingSenderId: '489954207593',
    projectId: 'resell-itv2',
    storageBucket: 'resell-itv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQ2jI5UZzQPJs8iBapr_bf4kRna__pRc',
    appId: '1:489954207593:ios:1c54f05c942c70d6963ff8',
    messagingSenderId: '489954207593',
    projectId: 'resell-itv2',
    storageBucket: 'resell-itv2.appspot.com',
    iosClientId: '489954207593-3e50j1kc6rih0qkee4fua3thpo9bcqpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.resellIt',
  );
}
